"""syllabus scope and question placement

Revision ID: 17fdea04c379
Revises: 75c18e1b07e5
Create Date: 2026-08-30 16:41:51.358210
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '17fdea04c379'
down_revision: str | None = '75c18e1b07e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_placement',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('board_unit_id', sa.String(length=36), nullable=True),
    sa.Column('curriculum_section', sa.String(length=32), nullable=True),
    sa.Column('tier', sa.String(length=48), nullable=True),
    sa.Column('skill_required', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reasoning', sa.String(length=1000), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_unit_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_placement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_placement_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_placement_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_placement_source'), ['source'], unique=False)

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syllabus_scope', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('syllabus_scope')

    with op.batch_alter_table('question_placement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_placement_source'))
        batch_op.drop_index(batch_op.f('ix_question_placement_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_placement_needs_review'))

    op.drop_table('question_placement')
    # ### end Alembic commands ###
