"""board unit, conditional chapter, concept family and 2B judgment

Revision ID: 458d5dfd3dd2
Revises: 
Create Date: 2026-08-28 13:35:52.765881
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '458d5dfd3dd2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_capture_asset',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('student_ref', sa.String(length=36), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('device_hint', sa.String(length=120), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('ink_profile', sa.JSON(), nullable=True),
    sa.Column('consent_class', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_capture_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_capture_asset_consent_class'), ['consent_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_capture_asset_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_capture_asset_sha256'), ['sha256'], unique=False)

    op.create_table('ml_crop',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('preproc_ver', sa.String(length=32), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_crop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_crop_asset_id'), ['asset_id'], unique=False)

    op.create_table('ml_disagreement',
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('source_a', sa.String(length=48), nullable=False),
    sa.Column('value_a', sa.String(length=16), nullable=False),
    sa.Column('source_b', sa.String(length=48), nullable=False),
    sa.Column('value_b', sa.String(length=16), nullable=False),
    sa.Column('resolved', sa.String(length=16), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_disagreement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_disagreement_crop_id'), ['crop_id'], unique=False)

    op.create_table('ml_human_label',
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.String(length=16), nullable=False),
    sa.Column('labeler_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('time_taken_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_human_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_human_label_crop_id'), ['crop_id'], unique=False)

    op.create_table('ml_prediction',
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('backend', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('distribution', sa.JSON(), nullable=False),
    sa.Column('argmax', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('calibrated', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.Integer(), nullable=True),
    sa.Column('auto_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_prediction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_prediction_backend'), ['backend'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_prediction_crop_id'), ['crop_id'], unique=False)

    op.create_table('school',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('board', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('ink_profile', sa.String(length=2000), nullable=True),
    sa.Column('training_consent', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_api_key'), ['api_key'], unique=True)

    op.create_table('taxonomy_node',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('label_i18n', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_version', 'code', name='uq_taxonomy_code')
    )
    with op.batch_alter_table('taxonomy_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_node_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxonomy_node_curriculum_version'), ['curriculum_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxonomy_node_path'), ['path'], unique=False)

    op.create_table('assessment',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('paper_code', sa.String(length=32), nullable=True),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_page_count', sa.Integer(), nullable=True),
    sa.Column('logical_page_count', sa.Integer(), nullable=True),
    sa.Column('imposition', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('declared', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('qmatrix_frozen_at', sa.String(length=40), nullable=True),
    sa.Column('qmatrix_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_source_sha256'), ['source_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_status'), ['status'], unique=False)

    op.create_table('board_unit_weight',
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('board_unit_id', sa.String(length=36), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source_doc_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['board_unit_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_version', 'board_unit_id', name='uq_board_unit_weight')
    )
    with op.batch_alter_table('board_unit_weight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_unit_weight_board_unit_id'), ['board_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_unit_weight_curriculum_version'), ['curriculum_version'], unique=False)

    op.create_table('book_chunk',
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('bucket', sa.String(length=1), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('normalised', sa.String(length=4000), nullable=False),
    sa.Column('stem_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_chunk_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_chunk_curriculum_version'), ['curriculum_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_chunk_stem_hash'), ['stem_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_chunk_subject_code'), ['subject_code'], unique=False)

    op.create_table('canonical_procedure',
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('subtopic_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('canonical_stem', sa.String(length=1000), nullable=False),
    sa.Column('stem_hash', sa.String(length=64), nullable=False),
    sa.Column('taught_verbatim', sa.Boolean(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_procedure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_procedure_curriculum_version'), ['curriculum_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_procedure_stem_hash'), ['stem_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_canonical_procedure_subject_code'), ['subject_code'], unique=False)

    op.create_table('chapter_board_unit',
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('board_unit_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['board_unit_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_version', 'chapter_id', name='uq_chapter_board_unit')
    )
    with op.batch_alter_table('chapter_board_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_board_unit_board_unit_id'), ['board_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_board_unit_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_board_unit_curriculum_version'), ['curriculum_version'], unique=False)

    op.create_table('prerequisite',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('requires_id', sa.String(length=36), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['requires_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'requires_id', name='uq_prereq')
    )
    with op.batch_alter_table('prerequisite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prerequisite_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prerequisite_requires_id'), ['requires_id'], unique=False)

    op.create_table('section',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'grade', 'name', name='uq_section')
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_school_id'), ['school_id'], unique=False)

    op.create_table('taxonomy_alias',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxonomy_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_alias_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_taxonomy_alias_node_id'), ['node_id'], unique=False)

    op.create_table('analysis_run',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('code_version', sa.String(length=40), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=32), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('logical_page',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('source_pdf_page', sa.Integer(), nullable=False),
    sa.Column('tile_bbox', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('image_uri', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'index', name='uq_logical_page')
    )
    with op.batch_alter_table('logical_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logical_page_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('question',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('section', sa.String(length=8), nullable=True),
    sa.Column('question_no', sa.String(length=12), nullable=False),
    sa.Column('sub_part', sa.String(length=12), nullable=True),
    sa.Column('choice_alt', sa.String(length=4), nullable=True),
    sa.Column('choice_group_id', sa.String(length=36), nullable=True),
    sa.Column('max_marks', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mark_step', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('question_type', sa.String(length=24), nullable=True),
    sa.Column('stem_text', sa.String(length=4000), nullable=True),
    sa.Column('stem_hash', sa.String(length=64), nullable=True),
    sa.Column('logical_page', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('board_unit_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('curriculum_section', sa.String(length=32), nullable=True),
    sa.Column('curriculum_section_title', sa.String(length=200), nullable=True),
    sa.Column('verified_against', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.String(length=40), nullable=True),
    sa.Column('concept_family_id', sa.String(length=36), nullable=False),
    sa.Column('concept_variant', sa.String(length=200), nullable=False),
    sa.Column('variant_hash', sa.String(length=64), nullable=False),
    sa.Column('skill_required', sa.String(length=200), nullable=True),
    sa.Column('complexity', sa.String(length=16), nullable=True),
    sa.Column('dependency_level', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(chapter_id IS NULL) = (curriculum_section IS NULL)', name='ck_question_chapter_pairing'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['board_unit_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['concept_family_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'address', name='uq_question_address')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_board_unit_id'), ['board_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_choice_group_id'), ['choice_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_concept_family_id'), ['concept_family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_stem_hash'), ['stem_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_variant_hash'), ['variant_hash'], unique=False)

    op.create_table('student_profile',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('roll_no', sa.String(length=16), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('consent_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'roll_no', name='uq_roll')
    )
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profile_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profile_section_id'), ['section_id'], unique=False)

    op.create_table('data_quality_flag',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_flag_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_flag_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_quality_flag_status'), ['status'], unique=False)

    op.create_table('mark_event',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('marks', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mark_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mark_event_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mark_event_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mark_event_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_mark_event_student_id'), ['student_id'], unique=False)

    op.create_table('question_judgment',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('field', sa.String(length=24), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=False),
    sa.Column('is_resolution', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_judgment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_judgment_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_judgment_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_judgment_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('question_skill',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_node.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'node_id', name='uq_question_skill')
    )
    with op.batch_alter_table('question_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_skill_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_skill_question_id'), ['question_id'], unique=False)

    op.create_table('question_tier',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=8), nullable=True),
    sa.Column('action_class', sa.String(length=24), nullable=True),
    sa.Column('familiarity', sa.Float(), nullable=True),
    sa.Column('familiarity_bucket', sa.String(length=1), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('conformal_set', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_tier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_tier_question_id'), ['question_id'], unique=False)

    op.create_table('test_session',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('instrument_version', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('item_order', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validity', sa.String(length=16), nullable=False),
    sa.Column('validity_detail', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_session_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_session_student_id'), ['student_id'], unique=False)

    op.create_table('item_response',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_response_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_response_session_id'), ['session_id'], unique=False)

    op.create_table('profile_result',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('holland_code', sa.String(length=3), nullable=True),
    sa.Column('differentiation', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Integer(), nullable=True),
    sa.Column('stream_fit', sa.JSON(), nullable=True),
    sa.Column('recommendation_withheld', sa.Boolean(), nullable=False),
    sa.Column('withheld_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_result_session_id'), ['session_id'], unique=True)

    op.create_table('scale_score',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('scale', sa.String(length=1), nullable=False),
    sa.Column('raw', sa.Float(), nullable=False),
    sa.Column('centered', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scale_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scale_score_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scale_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scale_score_session_id'))

    op.drop_table('scale_score')
    with op.batch_alter_table('profile_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_result_session_id'))

    op.drop_table('profile_result')
    with op.batch_alter_table('item_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_response_session_id'))
        batch_op.drop_index(batch_op.f('ix_item_response_item_id'))

    op.drop_table('item_response')
    with op.batch_alter_table('test_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_session_student_id'))
        batch_op.drop_index(batch_op.f('ix_test_session_school_id'))

    op.drop_table('test_session')
    with op.batch_alter_table('question_tier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_tier_question_id'))

    op.drop_table('question_tier')
    with op.batch_alter_table('question_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_skill_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_skill_node_id'))

    op.drop_table('question_skill')
    with op.batch_alter_table('question_judgment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_judgment_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_question_judgment_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_judgment_field'))

    op.drop_table('question_judgment')
    with op.batch_alter_table('mark_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mark_event_student_id'))
        batch_op.drop_index(batch_op.f('ix_mark_event_source'))
        batch_op.drop_index(batch_op.f('ix_mark_event_question_id'))
        batch_op.drop_index(batch_op.f('ix_mark_event_assessment_id'))

    op.drop_table('mark_event')
    with op.batch_alter_table('data_quality_flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_flag_status'))
        batch_op.drop_index(batch_op.f('ix_data_quality_flag_rule'))
        batch_op.drop_index(batch_op.f('ix_data_quality_flag_assessment_id'))

    op.drop_table('data_quality_flag')
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profile_section_id'))
        batch_op.drop_index(batch_op.f('ix_student_profile_school_id'))

    op.drop_table('student_profile')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_variant_hash'))
        batch_op.drop_index(batch_op.f('ix_question_stem_hash'))
        batch_op.drop_index(batch_op.f('ix_question_concept_family_id'))
        batch_op.drop_index(batch_op.f('ix_question_choice_group_id'))
        batch_op.drop_index(batch_op.f('ix_question_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_question_board_unit_id'))
        batch_op.drop_index(batch_op.f('ix_question_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_question_address'))

    op.drop_table('question')
    with op.batch_alter_table('logical_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logical_page_assessment_id'))

    op.drop_table('logical_page')
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_assessment_id'))

    op.drop_table('analysis_run')
    with op.batch_alter_table('taxonomy_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_alias_node_id'))
        batch_op.drop_index(batch_op.f('ix_taxonomy_alias_alias'))

    op.drop_table('taxonomy_alias')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_school_id'))

    op.drop_table('section')
    with op.batch_alter_table('prerequisite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prerequisite_requires_id'))
        batch_op.drop_index(batch_op.f('ix_prerequisite_node_id'))

    op.drop_table('prerequisite')
    with op.batch_alter_table('chapter_board_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_board_unit_curriculum_version'))
        batch_op.drop_index(batch_op.f('ix_chapter_board_unit_chapter_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_board_unit_board_unit_id'))

    op.drop_table('chapter_board_unit')
    with op.batch_alter_table('canonical_procedure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_procedure_subject_code'))
        batch_op.drop_index(batch_op.f('ix_canonical_procedure_stem_hash'))
        batch_op.drop_index(batch_op.f('ix_canonical_procedure_curriculum_version'))

    op.drop_table('canonical_procedure')
    with op.batch_alter_table('book_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_chunk_subject_code'))
        batch_op.drop_index(batch_op.f('ix_book_chunk_stem_hash'))
        batch_op.drop_index(batch_op.f('ix_book_chunk_curriculum_version'))
        batch_op.drop_index(batch_op.f('ix_book_chunk_bucket'))

    op.drop_table('book_chunk')
    with op.batch_alter_table('board_unit_weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_unit_weight_curriculum_version'))
        batch_op.drop_index(batch_op.f('ix_board_unit_weight_board_unit_id'))

    op.drop_table('board_unit_weight')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_source_sha256'))
        batch_op.drop_index(batch_op.f('ix_assessment_school_id'))

    op.drop_table('assessment')
    with op.batch_alter_table('taxonomy_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_node_path'))
        batch_op.drop_index(batch_op.f('ix_taxonomy_node_curriculum_version'))
        batch_op.drop_index(batch_op.f('ix_taxonomy_node_code'))

    op.drop_table('taxonomy_node')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_api_key'))

    op.drop_table('school')
    with op.batch_alter_table('ml_prediction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_prediction_crop_id'))
        batch_op.drop_index(batch_op.f('ix_ml_prediction_backend'))

    op.drop_table('ml_prediction')
    with op.batch_alter_table('ml_human_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_human_label_crop_id'))

    op.drop_table('ml_human_label')
    with op.batch_alter_table('ml_disagreement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_disagreement_crop_id'))

    op.drop_table('ml_disagreement')
    with op.batch_alter_table('ml_crop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_crop_asset_id'))

    op.drop_table('ml_crop')
    with op.batch_alter_table('ml_capture_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_capture_asset_sha256'))
        batch_op.drop_index(batch_op.f('ix_ml_capture_asset_school_id'))
        batch_op.drop_index(batch_op.f('ix_ml_capture_asset_consent_class'))

    op.drop_table('ml_capture_asset')
    # ### end Alembic commands ###
