"""book source: the contents-page oracle and upload provenance

Revision ID: 75c18e1b07e5
Revises: 5a1ebe98e396
Create Date: 2026-08-30 12:39:52.431918
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '75c18e1b07e5'
down_revision: str | None = '5a1ebe98e396'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_source',
    sa.Column('curriculum_version', sa.String(length=32), nullable=False),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('edition', sa.String(length=120), nullable=True),
    sa.Column('expected_sections', sa.JSON(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_version', 'subject_code', name='uq_book_source')
    )
    with op.batch_alter_table('book_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_source_curriculum_version'), ['curriculum_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_source_subject_code'), ['subject_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_source_subject_code'))
        batch_op.drop_index(batch_op.f('ix_book_source_curriculum_version'))

    op.drop_table('book_source')
    # ### end Alembic commands ###
