/**
 * Client-side "download" for principal reports and answer cards.
 * 🔧 In a real backend this would be a server-rendered PDF; here it builds
 * a small self-contained HTML file and saves it via a Blob, genuinely
 * downloadable and printable (Ctrl/Cmd+P → Save as PDF) without a PDF
 * library, which fits a UI-only build. Never called during render, only
 * from a click handler.
 */

import {
  attentionFor,
  buildStudentReport,
  classAveragePct,
  classRosterFull,
  findStudent,
  latestTest,
  mainBlockerFor,
  overallPctFor,
  questionSets,
  sectionComparison,
  testsConducted,
  topGapFor,
  type BoardXStudentReport,
} from "./avai-mock-data";

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function shell(title: string, subtitle: string, body: string): string {
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Inter, Arial, sans-serif; color: #1c2b30; background: #fbfbfa; margin: 0; padding: 32px; }
  .sheet { max-width: 880px; margin: 0 auto; background: #fff; border: 1px solid #e4e1d8; border-radius: 12px; overflow: hidden; }
  .head { padding: 24px 28px; border-bottom: 1px solid #e4e1d8; }
  .head h1 { margin: 0 0 4px; font-size: 22px; }
  .head p { margin: 0; color: #6b7278; font-size: 13.5px; }
  .body { padding: 24px 28px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 10px 0 20px; }
  th, td { text-align: left; padding: 7px 10px; border-bottom: 1px solid #edeae0; }
  th { color: #6b7278; font-weight: 600; text-transform: uppercase; font-size: 10.5px; letter-spacing: .04em; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  h2 { font-size: 15px; margin: 22px 0 6px; }
  .kv { display: flex; gap: 22px; flex-wrap: wrap; margin: 6px 0 4px; }
  .kv div { min-width: 120px; }
  .kv .l { font-size: 10.5px; text-transform: uppercase; color: #6b7278; letter-spacing: .04em; }
  .kv .v { font-size: 18px; font-weight: 700; }
  .foot { padding: 14px 28px; border-top: 1px solid #edeae0; font-size: 11.5px; color: #9aa0a4; }
  @media print { body { background: #fff; padding: 0; } .sheet { border: none; border-radius: 0; } }
</style></head>
<body>
  <div class="sheet">
    <div class="head"><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>
    <div class="body">${body}</div>
    <div class="foot">Generated by AVAI · demo build, this file is created in your browser, nothing is uploaded.</div>
  </div>
</body></html>`;
}

function triggerHtmlDownload(filename: string, html: string) {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Overall comparison across every section, the Classes overview's own
 * numbers, laid out as a downloadable report. */
export function downloadSectionsComparisonReport(testKey: string = latestTest.key) {
  const test = testsConducted.find((t) => t.key === testKey);
  const rows = sectionComparison
    .map((s) => ({ ...s, gap: topGapFor(s.section, testKey) }))
    .sort((a, b) => a.overallAttainment - b.overallAttainment);

  const body = `
    <h2>Section-by-section comparison</h2>
    <table>
      <thead><tr><th>Section</th><th class="num">Students</th><th class="num">Attainment</th><th class="num">Need attention</th><th class="num">Critical</th><th>Biggest gap</th></tr></thead>
      <tbody>
        ${rows
          .map(
            (r) =>
              `<tr><td>${esc(r.section)}</td><td class="num">${r.students}</td><td class="num">${r.overallAttainment}%</td><td class="num">${r.needAttention}</td><td class="num">${r.critical}</td><td>${esc(r.gap)}</td></tr>`
          )
          .join("")}
      </tbody>
    </table>`;

  triggerHtmlDownload(
    `AVAI-School-Comparison-${testKey}.html`,
    shell(`School Report, ${test?.name ?? testKey}`, `Every section compared, ${rows.reduce((n, r) => n + r.students, 0)} students · ${test?.date ?? ""}`, body)
  );
}

/** One class's KPIs and full roster, for the currently-viewed test. */
export function downloadClassReport(section: string, testKey: string) {
  const test = testsConducted.find((t) => t.key === testKey);
  const roster = [...(classRosterFull[section] ?? [])].sort((a, b) => Number(a.rollNo) - Number(b.rollNo));
  const attainment = Math.round(classAveragePct(section, testKey));
  const needAttention = roster.filter((s) => attentionFor(s, testKey) !== "On Track").length;
  const critical = roster.filter((s) => attentionFor(s, testKey) === "Intervention").length;
  const gap = topGapFor(section, testKey);

  const body = `
    <div class="kv">
      <div><div class="l">Students</div><div class="v">${roster.length}</div></div>
      <div><div class="l">Attainment</div><div class="v">${attainment}%</div></div>
      <div><div class="l">Need attention</div><div class="v">${needAttention}</div></div>
      <div><div class="l">Critical</div><div class="v">${critical}</div></div>
    </div>
    <p style="color:#6b7278;font-size:13px;">Biggest gap: <strong style="color:#1c2b30;">${esc(gap)}</strong></p>
    <h2>Students in ${esc(section)}</h2>
    <table>
      <thead><tr><th>Roll</th><th>Student</th><th class="num">Overall</th><th>Main blocker</th><th>Attention</th></tr></thead>
      <tbody>
        ${roster
          .map((s) => {
            const pct = Math.round(overallPctFor(s, testKey));
            return `<tr><td>${s.rollNo}</td><td>${esc(s.name)}</td><td class="num">${pct}%</td><td>${esc(mainBlockerFor(s, testKey))}</td><td>${esc(attentionFor(s, testKey))}</td></tr>`;
          })
          .join("")}
      </tbody>
    </table>`;

  triggerHtmlDownload(`AVAI-Class-${section}-${testKey}.html`, shell(`Class ${section} Report, ${test?.name ?? testKey}`, `${roster.length} students · ${test?.date ?? ""}`, body));
}

function reportBody(report: BoardXStudentReport): string {
  return `
    <div class="kv">
      <div><div class="l">Score</div><div class="v">${esc(report.score)}</div></div>
      <div><div class="l">Board exposure</div><div class="v">${report.boardExposureMarks} / ${report.totalBoardMarks}</div></div>
    </div>
    <p style="color:#6b7278;font-size:13px;">${esc(report.encouragingLine)}</p>
    <h2>Where you stand</h2>
    <table>
      <thead><tr><th>Chapter</th><th class="num">Scored</th><th class="num">Not scored</th><th>Board importance</th></tr></thead>
      <tbody>
        ${report.standing
          .map((r) => `<tr><td>${esc(r.chapter)}</td><td class="num">${r.scored} / ${r.outOf}</td><td class="num">${r.notScored}</td><td>${esc(r.boardImportance)}</td></tr>`)
          .join("")}
      </tbody>
    </table>
    <h2>${esc(report.patternLabel)}</h2>
    <p style="font-size:13.5px;"><strong>${esc(report.patternHeadline)}</strong><br/><span style="color:#6b7278;">${esc(report.patternBody)}</span></p>
    <h2>Where the marks went</h2>
    <table>
      <thead><tr><th>Chapter</th><th class="num">Score</th><th>What happened</th></tr></thead>
      <tbody>
        ${report.marksLost
          .map((m) => `<tr><td>${esc(m.chapter)}</td><td class="num">${esc(m.scoreLabel)}</td><td>${esc(m.subLabel)}, ${esc(m.insight)}</td></tr>`)
          .join("")}
      </tbody>
    </table>
    <h2>What to do next</h2>
    ${report.actionPlan
      .map(
        (a) =>
          `<p style="font-size:13.5px;"><strong>${esc(a.heading)}</strong></p><ul style="margin:4px 0 12px;padding-left:20px;font-size:13px;color:#3c4448;">${a.items
            .map((i) => `<li>${esc(i)}</li>`)
            .join("")}</ul>`
      )
      .join("")}
    <p style="font-size:11.5px;color:#9aa0a4;">${esc(report.evidenceNote)}</p>`;
}

/** One student's one-page BoardX report for the given test + subject. */
export function downloadStudentReport(studentId: string, testKey: string, subject: string) {
  const student = findStudent(studentId);
  const report = buildStudentReport(student!, testKey, subject);
  if (!student || !report) return;
  triggerHtmlDownload(
    `AVAI-${student.name.replace(/\s+/g, "-")}-${subject}-${testKey}.html`,
    shell(`${student.name}, ${subject} Report`, `${student.section} · Roll ${student.rollNo} · ${report.assessmentName}`, reportBody(report))
  );
}

/** A blank answer card (mark-entry sheet) for one test's subject paper, one
 * section, 8 students per printed sheet, mirrors the school's paper mark
 * entry sheets. Purely a template: it carries no marks, only question
 * headers and blank cells for OCR/manual entry after it's filled and
 * scanned back in. */
export function downloadAnswerCard(testKey: string, subject: string, section: string) {
  const test = testsConducted.find((t) => t.key === testKey);
  const roster = [...(classRosterFull[section] ?? [])].sort((a, b) => Number(a.rollNo) - Number(b.rollNo));
  const questions = questionSets[subject] ?? [];
  const perSheet = 8;
  const sheetCount = Math.max(1, Math.ceil(roster.length / perSheet));

  const headerRow = `<tr><th>Roll</th><th>Student</th>${questions.map((q) => `<th class="num">${esc(q.label)}<br/><span style="font-weight:400;color:#9aa0a4;">/${q.maxMarks}</span></th>`).join("")}<th class="num">Total</th></tr>`;

  const sheets = Array.from({ length: sheetCount }, (_, i) => {
    const rows = roster.slice(i * perSheet, i * perSheet + perSheet);
    const bodyRows = rows
      .map(
        (s) =>
          `<tr><td>${s.rollNo}</td><td>${esc(s.name)} <span style="color:#9aa0a4;font-size:11px;">(ABSENT ☐)</span></td>${questions
            .map(() => `<td class="num" style="min-width:34px;">&nbsp;</td>`)
            .join("")}<td class="num" style="font-weight:700;">&nbsp;</td></tr>`
      )
      .join("");
    return `<h2>Sheet ${i + 1} of ${sheetCount} · Roll ${rows[0]?.rollNo ?? ""}-${rows[rows.length - 1]?.rollNo ?? ""}</h2>
      <table><thead>${headerRow}</thead><tbody>${bodyRows}</tbody></table>`;
  }).join("");

  const total = questions.reduce((sum, q) => sum + q.maxMarks, 0);
  const body = `<p style="color:#6b7278;font-size:13px;">${questions.length} questions · Max ${total} · write the mark scored under each question; leave a row blank and tick ABSENT if the student didn't sit.</p>${sheets}`;

  triggerHtmlDownload(
    `AVAI-AnswerCard-${section}-${subject}-${testKey}.html`,
    shell(`Mark Entry Sheet, ${subject}`, `${test?.name ?? testKey} · Class X ${section} · ${roster.length} students`, body)
  );
}
